# Generated by Django 4.1.1 on 2022-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departments',
            fields=[
                ('name', models.CharField(max_length=128))
            ]
        ),
        migrations.CreateModel(
            name='employees',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('department', models.CharField(max_length=128)),
                ('dateOfJoining', models.PositiveBigIntegerField()),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
